.github/workflows/release.yml, lerna.json, package.json, packages/react-inbox/__tests__/Inbox.spec.tsx, packages/react-inbox/package.json, packages/react-inbox/src/components/Inbox/Bell.tsx, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Message/index.tsx, packages/react-inbox/src/components/Message/styled.tsx, packages/react-inbox/src/components/Messages/index.tsx, packages/react-inbox/src/hooks/use-inbox.ts, packages/react-inbox/src/hooks/use-messages.ts, packages/react-inbox/src/reducer.ts, packages/react-inbox/src/types.ts, packages/react-provider/package.json, packages/react-provider/src/index.tsx, packages/react-provider/src/reducer.ts, packages/react-provider/src/transports/base.ts, packages/react-provider/src/types.ts, packages/react-toast/package.json, packages/react-toast/src/components/Toast/index.tsx, packages/react-toast/src/hooks/index.ts, packages/storybook/.storybook/main.js, packages/storybook/package.json, packages/storybook/stories/inbox-with-toast.stories.tsx, packages/types/package.json
=> get components to talk to eachother

package.json
make sure not to verify we are logged in to npm and just use the token
> `Fix [#1]()`
=> fix lerna publish

.github/workflows/release.yml, lerna.json, package.json, packages/react-inbox/package.json, packages/react-inbox/src/components/Inbox/Bell.tsx, packages/react-provider/package.json, packages/react-toast/package.json, packages/storybook/package.json, packages/types/package.json
=> add icon themeing && better script name

.github/workflows/release.yml
=> fix command

packages/react-inbox/src/components/Message/index.tsx, packages/react-inbox/src/components/Message/styled.tsx
make maxwidth for message contents
> `Fix [#1]()`
=> fix spacing

packages/react-inbox/package.json, packages/react-inbox/src/components/Inbox/LazyTippy.tsx, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Messages/index.tsx, packages/react-inbox/src/components/Messages/loading.tsx, packages/react-inbox/src/components/Messages/styled.ts, yarn.lock
=> lazy tippy and loading skeleton

lerna.json, packages/components/package.json, packages/react-inbox/package.json, packages/react-provider/package.json, packages/react-toast/package.json, packages/storybook/package.json, packages/types/package.json
=> versionbump

package.json, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-provider/src/constants/index.ts, packages/react-provider/src/hooks/use-actions.ts, packages/react-provider/src/lib/events.ts, packages/react-provider/src/transports/types.ts, packages/react-toast/src/components/Body/helpers.tsx, packages/react-toast/src/components/Body/index.tsx, packages/storybook/stories/react-toast/with-click-action.stories.js, packages/storybook/stories/react-toast/with-transport.stories.js
=> [C-2468] Click Tracking Read Event

packages/react-inbox/package.json
=> both inbox and provider need urlql

packages/components/README.md, packages/components/src/index.html, packages/components/src/index.tsx, packages/react-inbox/src/components/Messages/index.tsx, packages/react-inbox/src/hooks/use-messages.ts, packages/storybook/stories/react-toast/with-transport.stories.js
=> Allow async init of Courier Components

lerna.json, packages/components/package.json, packages/react-inbox/package.json, packages/react-provider/package.json, packages/react-toast/package.json, packages/storybook/package.json, packages/types/package.json
=> version alpha 13

package.json, packages/react-inbox/package.json, packages/react-inbox/src/components/Actions/index.tsx, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Message/index.tsx, packages/react-inbox/src/components/Message/styled.tsx, packages/react-inbox/src/components/Messages/index.tsx, packages/react-inbox/src/components/Messages/loading.tsx, packages/react-inbox/src/components/OptionsDropdown/Options.tsx, packages/react-inbox/src/components/OptionsDropdown/index.tsx, packages/react-inbox/src/components/OptionsDropdown/styled.ts, packages/react-inbox/src/components/TabBar/index.tsx, packages/react-inbox/src/components/TabBar/styled.ts, packages/react-inbox/src/hooks/use-at-bottom.ts, packages/react-inbox/src/hooks/use-inbox.ts, packages/react-inbox/src/hooks/use-message-count.ts, packages/react-inbox/src/hooks/use-messages.ts, packages/react-inbox/src/hooks/use-track-event.ts, packages/react-inbox/src/reducer.ts, packages/react-inbox/src/types.ts, packages/react-provider/package.json, packages/react-provider/src/hooks/use-graphql-client.ts, packages/react-provider/src/index.tsx, packages/react-provider/src/middleware.ts, packages/storybook/stories/react-inbox/with-toast.stories.tsx, yarn.lock
=> trackEvent mutation and tabs

lerna.json, packages/components/package.json, packages/react-inbox/package.json, packages/react-provider/package.json, packages/react-toast/package.json, packages/storybook/package.json, packages/types/package.json
=> version 14

packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Messages/index.tsx, packages/react-inbox/src/hooks/use-inbox.ts, packages/react-inbox/src/reducer.ts, packages/react-provider/src/index.tsx, packages/react-provider/src/reducer.ts, packages/react-toast/src/components/Toast/index.tsx, packages/react-toast/src/hooks/index.ts, packages/react-toast/src/reducer.ts, packages/react-toast/tsconfig.json, packages/storybook/stories/react-toast/default.stories.tsx
=> localstorage

lerna.json, packages/components/package.json, packages/react-inbox/package.json, packages/react-provider/package.json, packages/react-toast/package.json, packages/storybook/package.json, packages/types/package.json
=> version 16

lerna.json, packages/components/package.json, packages/react-inbox/README.md, packages/react-inbox/package.json, packages/react-provider/package.json, packages/react-toast/README.md, packages/react-toast/package.json, packages/storybook/package.json, packages/types/package.json
=> Riley version18

packages/react-inbox/README.md
=> updated README

packages/react-inbox/README.md
=> suggested changes

packages/react-inbox/tsconfig.json, packages/react-provider/.npmignore, packages/react-provider/tsconfig.json, packages/react-toast/tsconfig.json
=> TSConfig Fix

lerna.json, packages/components/package.json, packages/react-inbox/package.json, packages/react-provider/package.json, packages/react-toast/package.json, packages/storybook/package.json, packages/types/package.json
=> Version Update

packages/react-provider/src/ws.ts
this.connected was always undefined
> `Fix [#1]()`
=> fix subscription

packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/index.ts, packages/react-inbox/src/types.ts, packages/react-provider/src/index.tsx, packages/react-provider/src/types.ts, packages/storybook/stories/react-inbox/with-toast.stories.tsx
allow passing in brand via props instead of async
> `Fix [#1]()`
=> branding update

lerna.json, packages/components/package.json, packages/react-inbox/package.json, packages/react-provider/package.json, packages/react-toast/package.json, packages/storybook/package.json, packages/types/package.json
=> version 23

packages/react-provider/src/types.ts
Brand Type needs to get reverted
> `Fix [#1]()`
=> Fix Brand Type

package.json, packages/react-inbox/README.md, packages/react-inbox/docs/1.overview.md, packages/react-inbox/docs/2.installation.md, packages/react-inbox/docs/3.props.md, packages/react-inbox/package.json, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/types.ts, packages/react-toast/README.md, packages/react-toast/docs/1.overview.md, packages/react-toast/docs/2.installation.md, packages/react-toast/docs/3.props.md, packages/react-toast/docs/4.hooks.md, packages/react-toast/package.json, packages/react-toast/src/components/Toast/index.tsx, packages/storybook/stories/inbox/index.stories.tsx, packages/storybook/stories/toast/index.stories.tsx, yarn.lock
- Use `concat-md` to make docs
- Pull in docs separatly into storybook
- Let toast props be available at root level
> `Fix [#1]()`
=> docs update / toast props

packages/react-inbox/src/components/Inbox/Bell.tsx, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Message/index.tsx, packages/react-inbox/src/components/TabList/index.tsx, packages/react-inbox/src/hooks/use-inbox-actions.ts, packages/react-inbox/src/reducer.ts, packages/react-toast/src/components/Actions/styled.ts, packages/react-toast/src/components/Body/helpers.tsx, packages/react-toast/src/components/Body/index.tsx, packages/react-toast/src/components/Body/styled.ts, packages/react-toast/src/components/Toast/index.tsx, packages/react-toast/src/components/Toast/styled.ts, packages/react-toast/src/components/index.ts, packages/react-toast/src/components/index.tsx, packages/react-toast/src/index.tsx, packages/react-toast/src/types.ts, packages/react-toast/tsconfig.json, packages/storybook/stories/inbox/with-toast.stories.tsx, packages/storybook/stories/toast/examples.stories.tsx
- Ability to import ToastBody so we can display in Studio/Brand
- Allow Toast to pass in brand
- Have Toast/Inbox use remote Brand config
- Style Tweaks
> `Fix [#1]()`
=> InApp Branding Update

packages/react-inbox/package.json, packages/react-inbox/tsconfig.json, packages/react-preferences/package.json, packages/react-preferences/tsconfig.json, packages/react-provider/package.json, packages/react-provider/tsconfig.json, packages/react-toast/package.json, packages/react-toast/src/index.tsx, packages/react-toast/tsconfig.json
=> Fix Typescript Types

packages/react-inbox/src/hooks/use-inbox-actions.ts, packages/react-provider/src/actions/track-event.ts, packages/react-provider/src/hooks/use-courier-actions.ts
=> fix batch events

.github/workflows/stage.yml, .github/workflows/staging.yml, package.json
On master, lets deploy staging commits with a "staging" tag 
> `Fix [#1]()`
=> Staging Deploy

.github/workflows/staging.yml, .github/workflows/test.yml, package.json
=> Riley stage2

.github/workflows/staging.yml, package.json
=> more staging

packages/react-toast/src/components/index.tsx
when showing inapp in logs preview, we need to rely on the remote brand
> `Fix [#1]()`
=> fix for remote brand

packages/react-toast/src/components/Body/helpers.tsx
=> fix icon rendering

packages/react-inbox/src/components/Message/index.tsx, packages/react-inbox/src/components/Message/styled.tsx
=> style tweaks

packages/react-inbox/src/components/Messages/Header/index.tsx
=> fix cog conditional

packages/react-inbox/package.json, packages/react-preferences/package.json, packages/storybook/package.json
=> Riley publish prefs

packages/react-preferences/src/components/PreferenceList.tsx
=> fix preferences theming

package.json
=> fix publish command for ci

packages/react-toast/package.json, packages/react-toast/src/components/Body/styled.ts, packages/storybook/stories/toast/examples.stories.tsx
=> fix overflow for textbox

packages/react-toast/package.json
=> try add back gitsha

packages/react-toast/src/components/Toast/index.tsx
prop name and type were wrong 
> `Fix [#1]()`
=> fix prop name

packages/react-toast/src/components/Toast/index.tsx, packages/storybook/stories/toast/examples.stories.tsx
=> make sure autoclose is a number

packages/react-provider/package.json, packages/react-provider/src/transports/courier/index.ts, packages/react-provider/src/transports/types.ts, packages/react-provider/src/ws.ts, yarn.lock
when we disconnect and reconnect we need to resubscribe so we need to keep track of all the subscriptions
> `Fix [#1]()`
=> ws reconnect

packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Messages/Header/styled.ts
=> prevent jiggle

packages/react-inbox/src/components/Messages/index.tsx, packages/react-inbox/src/components/Messages/styled.ts, packages/react-inbox/src/hooks/use-inbox.ts
=> fix ref for clickoutside

.github/workflows/staging.yml
=> rileyFixStagingDeploy

.github/workflows/staging.yml, packages/components/webpack.config.js, packages/react-provider/src/ws.ts
=> fix default envs

packages/components/src/components/index.tsx
prevent an error on querySelector
> `Fix [#1]()`
=> drone deploy was getting an error here

packages/components/src/components/index.tsx
trying to fix drone deploy bug where it says n.querySelector is not a function
> `Fix [#1]()`
=> make sure the element has querySelector

packages/react-inbox/src/components/Inbox/MobileWrapper.tsx, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Messages/index.tsx, packages/react-inbox/src/components/Messages/styled.ts, packages/react-inbox/src/hooks/index.ts, packages/react-inbox/src/hooks/use-event-listener.ts, packages/react-inbox/src/hooks/use-window-size.ts, packages/storybook/.storybook/main.js, packages/storybook/.storybook/preview.js, packages/storybook/package.json, packages/storybook/stories/inbox/index.stories.tsx, packages/storybook/stories/inbox/mobile.stories.tsx, packages/storybook/stories/inbox/mock-middleware.tsx, yarn.lock
responsive container for inbox
> `Fix [#1]()`
=> responsive inbox

packages/react-inbox/src/components/Message/styled.tsx
add text align left 
> `Fix [#1]()`
=> add text-align left for inbox alignment

packages/react-provider/src/index.tsx
=> fix window error for server

packages/react-inbox/src/actions/message-count.ts
=> fix unreadcount query

packages/components/src/index.html, packages/react-inbox/docs/0.props.md, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Message/index.tsx, packages/react-inbox/src/components/Message/types.ts, packages/react-inbox/src/components/Messages/index.tsx, packages/react-inbox/src/reducer.ts, packages/react-inbox/src/types.ts, packages/react-provider/src/transports/types.ts, packages/react-toast/src/components/Body/index.tsx, packages/react-toast/src/components/Body/styled.ts, packages/react-toast/src/defaults.ts, packages/react-toast/src/index.tsx, packages/react-toast/src/lib/index.ts, packages/react-toast/src/types.ts, packages/storybook/stories/toast/examples.stories.tsx
allow the ability to control whether a link opens in a new tab or not through a prop, renderprop, or soon the ability to configure via the studio
> `Fix [#1]()`
=> Riley new tab

packages/components/src/index.html, packages/components/src/index.tsx, packages/react-provider/src/index.tsx, packages/react-provider/src/transports/courier/constants.ts, packages/react-provider/src/transports/courier/index.ts, packages/react-provider/src/transports/courier/types.ts, packages/react-provider/src/types.ts, packages/react-provider/src/ws.ts, packages/storybook/stories/inbox/examples.stories.tsx, packages/storybook/stories/inbox/index.stories.tsx, packages/storybook/stories/inbox/mobile.stories.tsx, packages/storybook/stories/inbox/with-toast.stories.tsx, packages/storybook/stories/toast/with-transport.stories.tsx
update CourierProvider to take wsOptions which includes "url, connectionTimeout, onError"
> `Fix [#1]()`
=> wsoptions for onerror and timeout

packages/client-graphql/src/brands/index.ts, packages/client-graphql/src/events/index.ts, packages/client-graphql/src/messages/index.ts
=> Change void to undefined for GetBrand and GetMessages

packages/react-inbox/src/components/Message/index.tsx, packages/react-toast/src/components/Body/index.tsx, packages/storybook/stories/inbox/mock-middleware.tsx
the markdown library we use doesn't like being passed undefined
> `Fix [#1]()`
=> fix body error when no blocks/text exists

packages/client-graphql/src/banner/index.ts
void -> undefined
> `Fix [#1]()`
=> Unvoid getBanners

packages/react-inbox/README.md, packages/react-inbox/docs/0.props.md, packages/react-inbox/src/components/Messages/Header/styled.ts, packages/react-inbox/src/components/Messages/index.tsx, packages/react-inbox/src/components/index.ts, packages/react-inbox/src/types.ts, packages/storybook/stories/inbox/custom-header.tsx, packages/storybook/stories/inbox/index.stories.tsx
exporting the header will allow people to use it with our render prop
> `Fix [#1]()`
=> export header from inbox

package.json, packages/client-api/__tests__/inbox.spec.ts, packages/client-api/babel.config.js, packages/client-api/jest.config.js, packages/client-api/package.json, packages/client-api/src/inbox/index.ts, packages/client-api/src/index.ts, packages/client-api/src/lib/get-http-headers.ts, packages/client-api/src/types.ts, packages/client-api/tsconfig.json, tsconfig.json, yarn.lock
new package for new rest inbox api
> `Fix [#1]()`
=> client-api

packages/react-brand-designer/src/brand-designer/brand-controls.tsx, packages/react-brand-designer/src/brand-designer/logo-modal.tsx, packages/react-elements/src/components/modal/modal.tsx
Fixes the center alignment of the modal component and prevents the cancel button from refreshing the page.
=> [C-6465] (Brand Designer) Fix brand logo upload modal centering

packages/components/src/components/index.tsx, packages/react-brand-designer/src/brand-designer/brand-controls.tsx, packages/react-brand-designer/src/brand-designer/brand-designer.tsx, packages/react-brand-designer/src/brand-designer/brand-preview.tsx, packages/react-brand-designer/src/brand-designer/logo-modal.tsx
Fixes the upload logo button and shows the logo in the email preview.
=> [C-6473] Logo embed and preview support

packages/client-graphql/src/index.ts, packages/react-hooks/src/inbox/use-inbox-actions.ts, packages/react-provider/package.json, packages/react-provider/src/index.tsx, yarn.lock
react native doesn't have local storage so we want to polyfill it to prevent friction
> `Fix [#1]()`
=> Polyfill localstorage if it doesn't exist

package.json, packages/client-graphql/src/messages.ts, packages/react-hooks/src/inbox/types.ts, yarn.lock
Fixes mismatched type descriptions.
> `Fix [#1]()`
=> Fix IGetMessagesParams types

README.md, packages/react-brand-designer/README.md, packages/react-brand-designer/src/types.ts
Adds documentation for brand designer in README
> `Fix [#1]()`
=> Add docs for BrandDesigner

packages/react-brand-designer/src/clipboard-brand-designer.tsx
=> Allow theming of copy snippet button

packages/react-hooks/src/inbox/reducer.ts, packages/react-inbox/src/components/Messages/index.tsx, packages/react-inbox/src/components/TabList/index.tsx
=> debug logs

packages/react-preferences/src/components/FreeFooter.tsx
Removed underline from footer.
> `Fix [#1]()`
=> removed underline

packages/client-graphql/src/inbox/count.ts, packages/client-graphql/src/initial-state.ts, packages/components/__tests__/index.spec.tsx, packages/react-hooks/src/inbox/elemental-inbox/__tests__/reducer.spec.ts, packages/react-hooks/src/inbox/elemental-inbox/actions/fetch-unread-message-count.ts, packages/react-hooks/src/inbox/elemental-inbox/reducer.ts, packages/react-hooks/src/inbox/elemental-inbox/use-inbox-actions.ts, packages/react-hooks/src/inbox/use-inbox-actions.ts, packages/react-inbox/src/components/OptionsDropdown/index.tsx, packages/react-provider/src/hooks/use-courier-actions.ts, packages/react-provider/src/index.tsx, packages/react-provider/src/types.ts, packages/storybook/stories/inbox/2.0.stories.tsx, packages/storybook/stories/inbox/full-page-inbox-hooks.tsx, packages/storybook/stories/inbox/full-page-inbox.stories.tsx
- get unread message count payload type was wrong
- don't fetch "initial state" if we are only using hooks
> `Fix [#1]()`
=> fix hooks and actions

packages/react-hooks/docs/0.overview.md, packages/react-hooks/docs/1.types.md, packages/react-provider/docs/0.props.md, packages/react-provider/docs/1.listening-to-messages.md
Updates type docs, adds example usage, documents authorization header.
> `Fix [#1]()`
=> [C-7264] Elemental inbox documentation updates

packages/react-hooks/README.md, packages/react-hooks/docs/0.overview.md, packages/react-inbox-next/README.md, packages/react-provider/README.md
=> Build README files

packages/components/src/index.html, packages/react-hooks/src/inbox/types.ts, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Message/index.tsx, packages/react-inbox/src/types.ts, packages/storybook/stories/inbox/2.0.stories.tsx
make sure to update localstate
> `Fix [#1]()`
=> fix onclick for unread messages

packages/react-inbox/src/components/Messages2.0/Message.tsx, packages/react-inbox/src/hooks/use-local-storage-messages.ts, packages/react-provider/package.json, packages/react-provider/src/index.tsx, packages/react-provider/src/types.ts, yarn.lock
remove the polyfill as it was causing issues.  instead ignore localstorage stuff unless you pass it in or you're in the browser
> `Fix [#1]()`
=> try fix localstorage

packages/react-hooks/README.md, packages/react-hooks/docs/0.overview.md
=> Fix misleading docs that left out userId with auth token

packages/react-hooks/README.md, packages/react-hooks/docs/0.overview.md
=> Document inbox:write:events

packages/client-graphql/src/client.ts, packages/client-graphql/src/types.ts, packages/components/src/index.tsx, packages/react-hooks/src/inbox/actions/fetch-unread-message-count.ts, packages/react-hooks/src/inbox/actions/reset-last-fetched.ts, packages/react-hooks/src/inbox/elemental-inbox/use-inbox-actions.ts, packages/react-hooks/src/inbox/middleware.ts, packages/react-hooks/src/inbox/reducer.ts, packages/react-hooks/src/inbox/use-inbox-actions.ts, packages/react-hooks/src/inbox/use-inbox.ts, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Messages2.0/index.tsx, packages/react-provider/README.md, packages/react-provider/docs/0.props.md, packages/react-provider/package.json, packages/react-provider/src/hooks/use-courier-actions.ts, packages/react-provider/src/hooks/use-page-visible.ts, packages/react-provider/src/hooks/use-transport.ts, packages/react-provider/src/index.tsx, packages/react-provider/src/middleware.ts, packages/react-provider/src/reducer.ts, packages/react-provider/src/transports/base.ts, packages/react-provider/src/transports/courier/index.ts, packages/react-provider/src/transports/courier/types.ts, packages/react-provider/src/transports/types.ts, packages/react-provider/src/types.ts, packages/react-provider/src/ws.ts, packages/react-toast/src/hooks/index.ts, packages/storybook/stories/inbox/full-page-inbox-hooks.tsx, yarn.lock
A bunch of new features:
1. automatically reconnect if renewSession is called and we aren't connected
2. refetch data when we switch tabs
3. refetch data when we reconnect
4. support "read/unread/archive" events through websocket
> `Fix [#1]()`
=> create events with clientSourceId and listen for events

packages/react-inbox/src/components/Messages2.0/Header.tsx, packages/react-inbox/src/components/Messages2.0/LoadingIndicator.tsx, packages/react-inbox/src/components/Messages2.0/index.tsx
Implement styling tweaks requested by Ian.
https://www.loom.com/share/65357f146658401ead598669774d8e91
https://trycourier.slack.com/archives/C033L41M6P4/p1670615593553669?thread_ts=1670576887.924459&cid=C033L41M6P4
https://linear.app/trycourier/issue/C-7349/implement-loading-animation-from-ian
=> Tweak loading indicator styles

packages/react-provider/src/index.tsx, packages/react-provider/src/ws.ts, packages/storybook/stories/inbox/full-page-inbox.stories.tsx
we were historically unsubscribing but we should also disconnect on unmount
> `Fix [#1]()`
=> make sure to close the connection on unmount

packages/react-inbox/src/components/Messages2.0/Header.tsx, packages/react-inbox/src/components/Messages2.0/LoadingMore.tsx, packages/storybook/stories/inbox/2.0.stories.tsx
https://trycourier.slack.com/archives/C033L41M6P4/p1671047879828019?thread_ts=1670576887.924459&cid=C033L41M6P4
https://trycourier.slack.com/archives/C033L41M6P4/p1671049209805369?thread_ts=1670576887.924459&cid=C033L41M6P4
=> More styling tweaks from Ian

packages/react-hooks/src/preferences/use-preferences-actions.ts
This PR enables enables the hosted page to get around HMAC by using JWT as auth.
> `Fix [#1]()`
=> added authorization to preferences

packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Messages2.0/Header.tsx
new inbox styles ignored borderradius
> `Fix [#1]()`
=> make new inbox designs like borderradius

packages/components/src/components/PreferencePage.tsx
Offset page footer to allow all preference topics to be shown
https://www.loom.com/share/f67c2f9bedc14de48015fd6a13a52850
> `Fix [#1]()`
=> [C-8033] Fix hostedPage footer hiding topics

packages/react-preferences/src/components/PreferenceList.tsx, packages/react-preferences/src/components/PreferencesV4.tsx
Also added dividers to sections.
> `Fix [#1]()`
=> Added Inbox padding to Preferences list, 

packages/components/src/components/index.tsx, packages/components/src/index.tsx, packages/react-preferences/src/components/UnsubscribePage.tsx
Add list UI to unsubscribe page
Unrequired Topic:
Required Topic:
> `Fix [#1]()`
=> [C-8020] unsubscribing from lists

packages/react-provider/src/ws.ts
we need to return in the if statement
> `Fix [#1]()`
=> fix map with onReconnection

package.json, packages/client-api/__tests__/inbox.spec.ts, packages/client-api/src/lib/get-http-headers.ts, packages/client-api/tsconfig.json, packages/client-api/webpack.config.js, packages/client-graphql/src/__tests__/banner.spec.ts, packages/client-graphql/src/__tests__/messages.spec.ts, packages/client-graphql/src/client.ts, packages/client-graphql/src/inbox/__tests__/count.spec.ts, packages/client-graphql/src/inbox/__tests__/mark-all-read.spec.ts, packages/client-graphql/src/inbox/__tests__/message.spec.ts, packages/client-graphql/src/inbox/__tests__/messages.spec.ts, packages/client-graphql/src/inbox/__tests__/track-event.spec.ts, packages/client-graphql/src/types.ts, packages/client-graphql/tsconfig.json, packages/client-graphql/webpack.config.js, yarn.lock
Allow for API to send us the package version so that we can better triage issues and apply targetted patches.
=> [C-8196] puts client-version in allow list of custom headers

packages/react-inbox/src/components/Messages2.0/index.tsx, packages/react-preferences/src/components/PreferenceList.tsx
Fixed preferences padding for classic and 2.0 theme
> `Fix [#1]()`
=> Fixed preferences padding for classic and 2.0 theme

lerna.json, package.json, packages/client-graphql/package.json, packages/react-brand-designer/package.json, packages/react-elements/package.json, packages/react-hooks/package.json, packages/react-inbox/package.json, packages/react-preferences/package.json, packages/react-provider/package.json, packages/react-toast/package.json
lets try independent versioning
> `Fix [#1]()`
=> V62 + independent versioning

packages/client-graphql/package.json, packages/react-brand-designer/package.json, packages/react-elements/package.json, packages/react-hooks/package.json, packages/react-inbox/package.json, packages/react-preferences/package.json, packages/react-provider/package.json, packages/react-toast/package.json
=> chore(version 62.1): version 62.1

packages/client-graphql/package.json, packages/react-brand-designer/package.json, packages/react-elements/package.json, packages/react-hooks/package.json, packages/react-inbox/package.json, packages/react-inbox/src/components/Messages2.0/Header.tsx, packages/react-preferences/package.json, packages/react-provider/package.json, packages/react-toast/package.json
it was mistaken passing "event" to the function which was being mistaken as "fromWS" and not making the backend call
> `Fix [#1]()`
=> fix(mark all as read fix): fix mark all as read

packages/components/src/index.html, packages/react-brand-designer/package.json, packages/react-elements/package.json, packages/react-hooks/package.json, packages/react-inbox/package.json, packages/react-preferences/package.json, packages/react-provider/package.json
support react 18 with update to peer deps
> `Fix [#1]()`
=> chore(update peer dependencies): support react 18

packages/react-inbox/src/components/Messages2.0/index.tsx
removed console log
> `Fix [#1]()`
=> removed console log

packages/react-hooks/src/inbox/use-inbox-actions.ts, packages/react-hooks/src/inbox/use-inbox.ts, packages/react-provider/src/index.tsx
react 18 has new type for props with children
> `Fix [#1]()`
=> fix(react 18 props): fix for react 18 props with children

packages/storybook/stories/brand-designer/index.stories.tsx
=> chore(fix storybook): fix storybook for brand designer

packages/react-provider/src/hooks/use-client-source-id.ts
the key was being generated wrongly
> `Fix [#1]()`
=> fix(use-client-sourceid): fix the ls key for clientsource id

packages/react-toast/src/components/Toast/index.tsx
=> fix(toast defaults): fix toast defaults

packages/components/src/index.html, packages/react-inbox/README.md, packages/react-inbox/src/components/Messages2.0/Message.tsx, packages/react-inbox/src/components/Messages2.0/actions/MarkRead.tsx, packages/react-inbox/src/components/Messages2.0/actions/MarkUnread.tsx, packages/react-inbox/src/components/Messages2.0/actions/index.tsx, packages/react-inbox/src/components/Messages2.0/index.tsx, packages/react-toast/package.json, packages/react-toast/src/components/Body/index.tsx, packages/storybook/.storybook/main.js, yarn.lock
make actions mobile compat and uprade toast
> `Fix [#1]()`
=> feat(mobile actions): mobile inbox actions and toast upgrade

packages/react-inbox/src/components/Messages2.0/Message.tsx, packages/react-inbox/src/components/OptionsDropdown/Options.tsx, packages/react-toast/src/components/Body/index.tsx
fix bad react keys
> `Fix [#1]()`
=> fix(fix keys): fix react keys

packages/client-graphql/src/preferences.ts, packages/components/src/components/PreferencePage.tsx, packages/components/src/components/index.tsx, packages/components/src/index.tsx, packages/react-hooks/src/preferences/use-preferences-actions.ts, packages/react-preferences/src/components/PreferencesV4.tsx, packages/react-provider/src/types.ts
Allows `accountId` to be used in preferences query
=> [C-9790] adds accountId optional prop used in preferences

packages/react-preferences/src/components/Footer.tsx, packages/react-preferences/src/components/Header.tsx, packages/react-preferences/src/components/PreferenceList.tsx
Footer and header don't need to fetch the same thing twice.
=> fixes fetching pref page incorrectly

packages/react-provider/src/hooks/use-transport.ts, packages/react-provider/src/index.tsx, packages/react-provider/src/transports/courier/index.ts, packages/react-provider/src/transports/courier/types.ts, packages/react-provider/src/ws.ts
passes `account_id` to ws part 
> `Fix [#1]()`
=> fix(account_id): fixes passing account_id to the transport layer

packages/react-hooks/src/inbox/use-inbox.ts
=> fix(account_id): check inbox before using

packages/react-provider/src/hooks/use-transport.ts
re-create transport when accountId changes to get right subscriptions
> `Fix [#1]()`
=> adds accountId as deps to update transport

packages/client-graphql/docs/inbox/1.methods.md, packages/client-graphql/src/inbox/count.ts, packages/client-graphql/src/messages.ts, packages/react-hooks/src/inbox/elemental-inbox/types.ts, packages/react-hooks/src/inbox/elemental-inbox/use-inbox-actions.ts, packages/react-hooks/src/inbox/use-inbox-actions.ts
```
getUnreadMessageCount({ accountId: 'xxxxxx' });
```
=> fix(account_id): adds accountId in count query

packages/react-provider/src/index.tsx, packages/storybook/package.json, packages/storybook/stories/inbox/2.0.stories.tsx, packages/storybook/stories/inbox/index.stories.tsx, packages/storybook/stories/toast/index.stories.tsx, yarn.lock
add readme to storybook
> `Fix [#1]()`
=> chore(add readme to storybook): add readme

packages/client-graphql/docs/inbox/1.methods.md, packages/client-graphql/src/inbox/__tests__/count.spec.ts, packages/client-graphql/src/inbox/count.ts, packages/client-graphql/src/inbox/messages.ts, packages/client-graphql/src/messages.ts, packages/client-graphql/src/preferences.ts, packages/components/src/components/PreferencePage.tsx, packages/components/src/components/index.tsx, packages/components/src/index.tsx, packages/react-hooks/src/inbox/elemental-inbox/types.ts, packages/react-hooks/src/inbox/elemental-inbox/use-inbox-actions.ts, packages/react-hooks/src/inbox/types.ts, packages/react-hooks/src/inbox/use-inbox-actions.ts, packages/react-hooks/src/inbox/use-inbox.ts, packages/react-hooks/src/preferences/use-preferences-actions.ts, packages/react-inbox/src/components/Messages2.0/index.tsx, packages/react-inbox/src/types.ts, packages/react-preferences/src/components/PreferenceList.tsx, packages/react-preferences/src/components/PreferencesV4.tsx, packages/react-provider/src/hooks/use-transport.ts, packages/react-provider/src/index.tsx, packages/react-provider/src/transports/courier/index.ts, packages/react-provider/src/transports/courier/types.ts, packages/react-provider/src/types.ts, packages/react-provider/src/ws.ts
=> [C-10110] changes `account` to `tenant`

README.md
=> Improve V4 Changelog

packages/components/README.md
Adding update to README for window.courier.preferences
> `Fix [#1]()`
=> added preferences to the components readme

packages/components/README.md, packages/components/src/index.html, packages/components/src/index.tsx, packages/react-preferences/src/components/PreferenceList.tsx
- passing tenantId and draft to PreferenceV4 for <courier-preferences />
- debug event `.on(*, ()=>{})`
- Preference retrieving data into readme
=> Misc Preference + Tenant updates

packages/client-graphql/README.md
update graphql-client docs
Fixes DEV-14
=> updating graphql-client docs to include preferencesApi

.github/workflows/release.yml, .github/workflows/staging.yml, packages/components/README.md, packages/components/webpack.config.js
upload assets to new S3/CDN for performance improvements
> `Fix [#1]()`
=> perf(new cdn): add new CDN to serve code from vs s3

.github/workflows/release.yml, .github/workflows/staging.yml
=> ci(fix s3 upload): fix s3 upload as we don't need acl

packages/react-inbox/README.md, packages/react-provider/src/hooks/use-courier-actions.ts, packages/storybook/stories/inbox/2.0.stories.tsx
=> fix(another authentiction fix): fix useeffect referencing wrong variable

packages/components/README.md
update CDN location
> `Fix [#1]()`
=> Update README.md for CDN

packages/components/src/components/PreferencePage.tsx
=> overflow-y:hidden on PreferencePage

packages/components/src/components/index.tsx, packages/react-toast/src/components/Toast/index.tsx
Fixing the toast config issue in components
> `Fix [#1]()`
=> toast config, deprecating nested config

package.json, packages/components/src/components/CourierSdk.tsx, packages/components/src/index.tsx, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Messages2.0/Header.tsx, packages/react-inbox/src/hooks/use-local-storage-messages.ts, packages/react-preferences/src/components/DigestSchedule.tsx, packages/react-preferences/src/components/PreferenceTemplate.tsx, packages/react-preferences/src/components/PreferencesV4.tsx, packages/react-preferences/src/components/Status.tsx, packages/react-preferences/src/types.ts, packages/react-preferences/src/utils/format_digest.ts, packages/react-provider/src/hooks/use-courier-actions.ts, packages/react-provider/src/hooks/use-courier.ts, packages/react-provider/src/index.tsx, packages/react-provider/src/types.ts, packages/react-toast/src/components/Toast/index.tsx, packages/react-toast/src/hooks/index.ts, yarn.lock
add courierjs to react-provider useCourier and fix types for useCourier
> `Fix [#1]()`
=> feat(add courierjs): add courierjs and fix typings for useCourier

package.json, packages/react-provider/package.json, packages/react-provider/src/hooks/use-courier-actions.ts
fix package.json for courier-js
create clientkey if we only have auth token
> `Fix [#1]()`
=> fix(fix deps and clientkey): fix client key and deps

packages/react-hooks/package.json
update exports for hooks
> `Fix [#1]()`
=> fix(fix hook exports'): fix hook exports

packages/react-inbox/src/components/Messages2.0/actions/index.tsx
Fixing inbox label
> `Fix [#1]()`
=> fixing mark as unread leable

packages/react-inbox/src/components/Messages2.0/Header.tsx, packages/storybook/stories/inbox/index.stories.tsx
updating labels for close inbox
> `Fix [#1]()`
=> updating labels for close inbox

packages/react-preferences/src/components/PreferencesV4.tsx
Schedule changes need to pass tenantId
=> adding tenantId for schedule change

packages/react-inbox/src/components/Messages2.0/index.tsx, packages/react-inbox/src/types.ts, packages/storybook/stories/inbox/2.0.stories.tsx, packages/storybook/stories/inbox/index.stories.tsx, packages/storybook/stories/inbox/with-toast.stories.tsx
=> C-13252 - feat(add render prop loading more): add new render prop for loading more

packages/react-provider/README.md, packages/react-provider/docs/1.listening-to-messages.md, packages/react-provider/docs/2.dark-mode.md
=> docs: fix various typos in docs

README.md, packages/client-graphql/README.md, packages/components/README.md, packages/react-elements/README.md, packages/react-hooks/README.md, packages/react-inbox/README.md, packages/react-preferences/README.md, packages/react-provider/README.md, packages/react-toast/README.md
=> docs: add deprecation warning to README
