packages/components/package.json, packages/react-preferences/README.md, packages/react-preferences/babel.config.js, packages/react-preferences/docs/1.overview.md, packages/react-preferences/package.json, packages/react-preferences/src/components/ChannelPreferences.tsx, packages/react-preferences/src/components/SnoozePreference.tsx, packages/react-preferences/src/components/Status.tsx, packages/react-preferences/src/components/StyledToggle.tsx, packages/react-preferences/src/components/index.ts, packages/react-preferences/src/components/preferences.tsx, packages/react-preferences/src/components/types.ts, packages/react-preferences/src/hooks/use-preferences.ts, packages/react-preferences/src/index.ts, packages/react-preferences/tsconfig.json, packages/storybook/stories/react-preferences/with-preference-widget.stories.tsx, yarn.lock
```typescript
export function ConsumerComponent(): React.ReactElement {
const preferenceTemplateId = "YOUR_TEMPLATE_ID";
const { CLIENT_KEY, USER_ID } = {CLIENT_KEY:"YOUR_CLIENT_KEY", USER_ID: "YOUR_RECIPIENT_ID"};
return (
<CourierProvider clientKey={CLIENT_KEY} userId={USER_ID}>
<Preferences preferenceTemplateId={preferenceTemplateId}></Preferences>
</CourierProvider>
);
}
```
=> [C-2527] adds preference widget component

packages/components/src/index.html, packages/react-inbox/src/components/Actions/styled.ts, packages/react-inbox/src/components/Inbox/TippyStyle.ts, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Message/index.tsx, packages/react-inbox/src/components/Message/styled.tsx, packages/react-inbox/src/components/OptionsDropdown/index.tsx, packages/react-inbox/src/reducer.ts, packages/react-inbox/src/style.css, packages/react-provider/src/transports/types.ts, packages/react-provider/src/ws.ts, packages/react-toast/src/components/Actions/styled.ts, packages/react-toast/src/components/Body/helpers.tsx, packages/react-toast/src/components/Body/index.tsx, packages/react-toast/src/components/Body/styled.ts, packages/react-toast/src/components/Toast/index.tsx, packages/react-toast/src/components/Toast/styled.ts, packages/react-toast/src/index.tsx, packages/storybook/stories/inbox/examples.stories.tsx, packages/storybook/stories/inbox/with-toast.stories.tsx, packages/storybook/stories/toast/examples.stories.tsx
- Disabling message icon doesn't hide the icon in inbox or toast
- Simplify the branding of the toast message to avoid ugly inverted button state. In v1, let's just have the both buttons be rgb(52, 69, 99) to match the toast title font color
- Change Inbox design font from Nunito to Nunito Sans.
- Make the toast top bar link to the primary color
> `Fix [#1]()`
=> inapp updates

packages/react-inbox/src/components/Messages/loading.tsx
right now the loading placeholder is smaller than a message which makes the inbox size jump between tabs.  this fixes that.
> `Fix [#1]()`
=> better loading

packages/react-preferences/src/components/preferences.tsx, packages/react-preferences/src/hooks/use-preferences.ts, packages/react-preferences/src/types.ts
- c-3005 introduced some changes to how we persist information on graph. This incorporates those. I forgot to raise PR last cycle
=> [C-3005] incorporate graqhql query changes

.github/workflows/release.yml, .github/workflows/staging.yml
s3 upload should not delete old files now that we have staging.js
- [ x] Bug fix (non-breaking change that fixes an issue)
> `Fix [#1]()`
=> s3 upload should not delete old files now that we have staging.js

packages/components/README.md, packages/components/src/components/index.tsx, packages/components/src/index.html, packages/components/src/index.tsx, packages/react-inbox/docs/0.props.md, packages/react-inbox/src/components/Message/helpers.ts, packages/react-inbox/src/components/Message/index.tsx, packages/react-inbox/src/components/Messages/Header/index.tsx, packages/react-inbox/src/components/Messages/index.tsx, packages/react-inbox/src/components/OptionsDropdown/Options.tsx, packages/react-inbox/src/components/OptionsDropdown/index.tsx, packages/react-inbox/src/reducer.ts, packages/react-inbox/src/types.ts, packages/react-provider/src/hooks/use-courier-actions.ts, packages/react-toast/src/components/Body/index.tsx, packages/storybook/stories/inbox/index.stories.tsx, packages/storybook/stories/toast/examples.stories.tsx
- support labels in Inbox for `mark as read` `mark as unread` `mark all as read` `back to inbox`
- fix action buttons > 1 from being next to eachother on the same line
- support `window.courier.inbox.setConfig` to dynamically update config
- make click outside of "message options" close tooltip
> `Fix [#1]()`
=> inapp updates for inbox/toast

packages/react-inbox/README.md, packages/react-inbox/docs/0.props.md, packages/react-inbox/docs/2.render-props.md, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/types.ts, packages/storybook/stories/inbox/custom-components.tsx, packages/storybook/stories/inbox/index.stories.tsx
Expose bell via props
Storybook screenshot where bell was custom rendered:
> `Fix [#1]()`
=> C-4972: Expose bell rendering via props

packages/react-inbox/__mocks__/api/brand.ts, packages/react-inbox/__tests__/closed/index.tsx, packages/react-provider/src/actions/brand.ts
Fetch default in app brand (backend falls back on default brand if default inapp isn't configured so its 100% backwards compatible)
> `Fix [#1]()`
=> [C-4945] fetches default brand in `in-app` 

packages/client-graphql/README.md, packages/client-graphql/src/messages/index.ts, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Messages/index.tsx, packages/react-inbox/src/hooks/use-inbox-actions.ts, packages/react-provider/src/transports/types.ts
support `tags` as a filter param in our graphql calls
> `Fix [#1]()`
=> list messages and message count with tags

packages/react-hooks/src/inbox/reducer.ts, packages/react-hooks/src/inbox/types.ts, packages/react-inbox/src/components/Inbox/index.tsx, packages/react-inbox/src/components/Messages/index.tsx, packages/react-inbox/src/components/TabList/index.tsx, packages/react-inbox/src/types.ts
tabs were stored in reducer/context which meant they couldn't be updated via props.  we need them to be updated via props for localization
> `Fix [#1]()`
=> allow updating tabs through props

packages/client-graphql/babel.config.js, packages/client-graphql/src/__tests__/banner.spec.ts, packages/client-graphql/src/__tests__/index.spec.ts, packages/client-graphql/src/banner.ts, packages/client-graphql/src/brands.ts, packages/client-graphql/src/client.ts, packages/client-graphql/src/events.ts, packages/client-graphql/src/inbox/__tests__/count.spec.ts, packages/client-graphql/src/inbox/__tests__/mark-all-read.spec.ts, packages/client-graphql/src/inbox/__tests__/message.spec.ts, packages/client-graphql/src/inbox/__tests__/messages.spec.ts, packages/client-graphql/src/inbox/__tests__/track-event.spec.ts, packages/client-graphql/src/inbox/count.ts, packages/client-graphql/src/inbox/index.ts, packages/client-graphql/src/inbox/mark-all-read.ts, packages/client-graphql/src/inbox/message.ts, packages/client-graphql/src/inbox/messages.ts, packages/client-graphql/src/inbox/track-event.ts, packages/client-graphql/src/index.ts, packages/client-graphql/src/messages.ts, packages/client-graphql/src/messages/index.ts, packages/client-graphql/src/preferences.ts, packages/react-hooks/src/inbox/use-inbox-actions.ts
this adds new exports to client-graphql for Inbox.  currently we have Messages but Inbox is what will be used for the new inbox apis
> `Fix [#1]()`
=> add new inbox to clientgraphql

packages/react-hooks/docs/0.overview.md, packages/react-hooks/docs/1.types.md, packages/react-hooks/src/inbox/elemental-inbox/use-inbox-actions.ts, packages/react-provider/docs/0.props.md, packages/react-provider/src/transports/courier/index.ts, packages/react-provider/src/types.ts, packages/react-provider/src/ws.ts
Adds `renewSession` method to the elemental inbox hooks. This allows websocket connections with short lived authorization tokens to renew their sessions indefinitely.
Also includes updates and improvements to related docs.
> `Fix [#1]()`
=> [C-7266] React hooks renew session function + doc updates

packages/react-inbox/src/components/Messages2.0/Message.tsx, packages/react-provider/src/index.tsx, packages/react-provider/src/transports/types.ts, packages/react-toast/src/components/Body/index.tsx, packages/react-toast/src/components/Body/styled.ts, packages/react-toast/src/hooks/index.ts
- we're moving away from buttons and want to support clicking on the entire message
- only fire "deliverfed" from a toast vs the provider
> `Fix [#1]()`
=> make entire toast clickable

packages/react-preferences/src/components/PreferencePage.tsx
Oped In / Out text now updates when a user updates their preferences.
https://user-images.githubusercontent.com/63924603/205432850-3c07858d-60eb-482d-bd9d-c8fbb295239c.mov
> `Fix [#1]()`
=> Updated opted in/out text

packages/react-preferences/src/components/PreferencePage.tsx
Hosted preference page buttons now match default brand.
> `Fix [#1]()`
=> Added branded buttons

packages/react-preferences/src/components/PreferencesV4.tsx, packages/react-preferences/src/components/UnsubscribePage.tsx
This PR handles a user who has not published their preference page. An unpublished preference page prevents the unsubscribe page and the preference page from loading. 
> `Fix [#1]()`
=> Handle Null preference page

packages/react-preferences/src/components/Header.tsx, packages/react-preferences/src/components/PreferencesV4.tsx
Spacing fixes for hosted page, added dividing lines between subscription topics
> `Fix [#1]()`
=> [C-7828] hosted page spacing and dividing lines

packages/react-preferences/src/components/PreferencesV4.tsx
Remove the ability to change communication preferences if a topic is required
> `Fix [#1]()`
=> [C-8039] Make required topics have at least 1 channel in preferences

packages/react-preferences/src/components/DigestSchedule.tsx, packages/react-preferences/src/components/PreferencesV4.tsx, packages/react-preferences/src/types.ts
Add digest schedule options to preferences hostedPage
> `Fix [#1]()`
=> Feat: [C-9211] Add digest schedules to hostedPreferences

packages/client-graphql/src/inbox/index.ts, packages/client-graphql/src/inbox/track-event.ts, packages/components/README.md, packages/components/__tests__/index.spec.tsx, packages/components/src/components/CourierSdk.tsx, packages/components/src/index.html, packages/components/src/index.tsx, packages/react-hooks/README.md, packages/react-hooks/docs/2.events.md, packages/react-hooks/src/inbox/__tests__/reducer.spec.ts, packages/react-hooks/src/inbox/actions/unpin-message.ts, packages/react-hooks/src/inbox/reducer.ts, packages/react-hooks/src/inbox/use-inbox-actions.ts, packages/react-hooks/src/inbox/use-inbox.ts, packages/react-inbox/src/hooks/use-on-screen.ts, packages/react-provider/src/hooks/use-courier-actions.ts, packages/react-provider/src/index.tsx, packages/react-provider/src/types.ts
- create unpinMessage action
- add "onEvent" listener to know when events happen
- add more details to window.courier.inbox that has state and actions so embedded users can create actions
- add renewSession as an action to window.courier.renewSession
> `Fix [#1]()`
=> feat(unpinning): support unpinning a message via api

packages/components/src/index.html, packages/react-hooks/src/inbox/reducer.ts, packages/react-inbox/src/components/Inbox/TippyGlobalStyle.ts, packages/react-inbox/src/components/Messages2.0/LoadingMessages.tsx, packages/react-inbox/src/components/Messages2.0/index.tsx, packages/react-preferences/src/components/PreferenceList.tsx, packages/react-preferences/src/components/PreferencesV4.tsx
- remove unnecessary css from preferences so it can import from the main theme
- support inbox as a channel to select in preferences
> `Fix [#1]()`
=> Riley prefs

packages/react-preferences/src/components/PreferencesV4.tsx
=> [C-9943] fixes inbox preferences Opted Out by default

packages/client-api/package.json, packages/client-graphql/package.json, packages/components/package.json, packages/react-brand-designer/package.json, packages/react-elements/package.json, packages/react-hooks/package.json, packages/react-inbox-next/package.json, packages/react-inbox/package.json, packages/react-preferences/package.json, packages/react-provider/package.json, packages/react-toast/package.json
- remove the typings folder during `yarn clean` to re-generate them correctly
=> Feat: remove typings during clean command

packages/client-graphql/src/inbox/messages.ts, packages/react-hooks/src/inbox/types.ts, packages/react-hooks/src/inbox/use-inbox.ts, packages/react-inbox/src/components/Messages2.0/index.tsx, packages/react-inbox/src/types.ts, packages/react-provider/src/index.tsx, packages/react-provider/src/transports/types.ts, packages/react-provider/src/types.ts, packages/react-provider/src/ws.ts
Allows specifying accountId in `courier-provider` 
```tsx
<CourierProvider
clientKey="<your_client_key>"
userId="<your_user_id>"
accountId="<your_account_id>"
>
<Inbox theme={theme} {...props} />
</CourierProvider>
```
This inbox will fetch and render all messages that were sent to user+accountId. If you don't specify accountId, your inbox will receive all messages sent to the user.
=> feat: allows filtering inbox by accountId

packages/react-provider/src/hooks/use-page-visible.ts
👋  from hipages 😃 
React Native environments don't have the `document` global which means the provider is not really useable in RN projects. Stubbing `document` in RN projects breaks other libraries as they also check for its presence to turn on/off browser-specific features.
=> fix: check if `document` is defined in `use-page-visible` hook

packages/react-hooks/src/inbox/use-inbox-actions.ts, packages/react-inbox/README.md
When using Inbox with views, unread and read weren't getting applied properly. This PR fixes that by applying the GetInboxMessagesParams.status to fetchMessages()
=> fixing read and unread logic to include new type of IGetInboxMessagesParams.status

packages/react-preferences/src/components/DigestSchedule.tsx, packages/react-preferences/src/types.ts, packages/react-preferences/src/utils/format_digest.ts
Allows updated digest schedules that are returning the start key to display in local time calculated by the browser.
=> adding in local time on the prefernce page for digest schedules

.github/workflows/test.yml, packages/react-provider/src/types.ts
This PR adds missing `renderActionsAsButtons` prop to `Brand.inapp` type.
I've also added `yarn types` check to the PR workflow so you can catch these errors earlier,,
> `Fix [#1]()`
=> fix: added missing renderActionsAsButtons to types

packages/react-inbox/README.md
update inbox readme to include formatDate example
=> update readme to include formatDate example

packages/react-inbox/src/components/Messages2.0/index.tsx, packages/react-inbox/src/components/Messages2.0/styled.tsx
Scroll bars appear on windows // scroll enabled because `overflow: scroll` changing to overflow: auto
> `Fix [#1]()`
=> fixing scroll bars

packages/react-inbox/src/components/Messages2.0/Message.tsx, packages/react-inbox/src/components/Messages2.0/actions/index.tsx
When exposing an archived view, we should make the messages look uniform. 
> `Fix [#1]()`
=> making archived messages appear to be read regardless of read status

packages/client-graphql/src/inbox/index.ts, packages/client-graphql/src/inbox/track-event.ts, packages/components/src/index.html, packages/components/src/index.tsx, packages/react-hooks/src/inbox/actions/add-tag.ts, packages/react-hooks/src/inbox/actions/remove-tag.ts, packages/react-hooks/src/inbox/reducer.ts, packages/react-hooks/src/inbox/use-inbox-actions.ts, packages/react-provider/src/transports/types.ts, packages/react-provider/src/types.ts
allow adding and removing tags
> `Fix [#1]()`
=> feat(add and remove tags): allow adding and removing tags

packages/react-hooks/src/preferences/types.ts, packages/react-preferences/src/components/PreferencesV4.tsx
- When using Customize Delivery Channel, the default would put all options selected even if the defaults had less options.
- When a topic was required, we wouldn't show Customize Delivery Channel at all. Now, we will show it, but not let you de-select all channels.
> `Fix [#1]()`
=> fixing extra channels and exposing customize on Required topics

packages/react-preferences/README.md, packages/react-preferences/docs/0.overview.md, packages/react-preferences/docs/1.easy-usage.md
Updating React Preferences README to include CourierProvider Example and note about prop-types
=> adding in prop types and courierProvider to example

packages/client-graphql/src/inbox/messages.ts
Pins are always returned from getInboxMessages
=> adding pinned to GetInboxMessages

packages/react-provider/src/hooks/use-listen-for-transport.ts, packages/react-provider/src/index.tsx, packages/react-toast/src/hooks/index.ts
Hoisting delivery tracking to CourierProvider from Toast; currently the docs already says this, but the listener is only attached when using Toast.
=> hoisting createTrackEvent(deliveryTrackingId)

packages/components/README.md, packages/components/src/index.tsx, packages/react-hooks/README.md, packages/react-hooks/docs/2.events.md, packages/react-inbox/src/components/Messages2.0/Message.tsx, packages/react-inbox/src/components/Messages2.0/index.tsx, packages/react-provider/src/types.ts, packages/react-toast/src/components/Body/index.tsx, packages/react-toast/src/components/Toast/index.tsx, packages/react-toast/src/components/index.tsx, packages/storybook/stories/client-graphql/examples/messages.tsx, packages/storybook/stories/toast/examples.stories.tsx, packages/storybook/stories/toast/index.stories.tsx
Fixes #582 to provide access to all of the data within the Inbox provider's data mapping
=> adding the data mapping payload to the onroutechange handler

packages/react-inbox-next/package.json, packages/react-inbox/package.json, packages/react-toast/package.json, yarn.lock
Updating markdown-to-jsx to 7.7.3 due to Cross-Site Scripting vulnerability.
> https://github.com/trycourier/courier-react/issues/604
=> chore: upgrade markdown-to-jsx to latest version

.github/workflows/test.yml
> This request has been automatically failed because it uses a deprecated version of `actions/cache: v2`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions.
[NOT a breaking-change](https://github.com/marketplace/actions/cache#:~:text=Changes%20in%20these%20release%20are%20fully%20backward%20compatible.). 
Fix [#1](https://github.com/trycourier/courier-react/actions/runs/13653824653/job/38168229202?pr=621)
=> chore: bump actions/cache to v4

packages/react-hooks/package.json
The `jwt-decode` library is imported in the `react-hooks` package.
However, the library isn't added to the package's package.json file.
```
TypeError: (0 , _jwtDecode.jwtDecode) is not a function...
```
This change adds the `jwt-decode` library to the `react-hooks` package.
> `Fix [#1]()`
=> fix: add missing jwt-decode package

packages/react-preferences/package.json, packages/react-preferences/src/utils/format_digest.ts, yarn.lock
- The idea of this PR is to make sure digest schedule date, into Notification Preferences page, will be reflecting the user browser timezone. 
> `Fix [#1]()`
=> fix: ensure preference experience page will show digest time in browser timezone
